spring:
  datasource:
    url: jdbc:mysql://picpay-qa-estag-playground.cixwtib85ctv.us-east-1.rds.amazonaws.com:3306/ms_contacts
    username: udba_alef
    password: Lunna230617$#@!
    driver-class-name: com.mysql.cj.jdbc.Driver # Use a classe de driver MySQL apropriada
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true # Exibir consultas SQL no console (opcional)
    hbm2ddl:
      auto: update 